config/routes.rb
Rails.application.routes.draw do
  root to: 'ratings#index'
  resources :ratings do
    resources :recipes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  has_many :recipes, dependent: :destroy

before_save(:titleize_rating)

private
  def titleize_rating
    self.difficulty = self.difficulty.titleize
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true
  belongs_to :rating

  scope :search, -> (title) {where("title like ?", "%#{title}%")}

  before_save(:titleize_recipe)

  private
  def titleize_recipe
    self.title = self.title.titleize
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def index
    @ratings = Rating.all
    render :index
  end

  def new
    @rating = Rating.new
    render :new
  end

  def create
    @rating = Rating.new(rating_params)
    if @rating.save
      redirect_to ratings_path
    else
      render :new
    end

  end

  def edit
    @rating = Rating.find(params[:id])
    render :edit
  end

  def show
    @rating = Rating.find(params[:id])
    if params[:search]
      @recipes = @rating.recipes.search(params[:search])
    else
      @recipes = @rating.recipes
    end
    render :show
  end

  def update
    @rating= Rating.find(params[:id])
    if @rating.update(rating_params)
      redirect_to ratings_path
    else
      render :edit
    end
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to ratings_path
  end

  private
  def rating_params
    params.require(:rating).permit(:difficulty)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @rating = Rating.find(params[:rating_id])
    @recipe = @rating.recipes.new
    render :new
  end

  def create
    @rating = Rating.find(params[:rating_id])
    @recipe = @rating.recipes.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe succesfully added! MMMMMMmmmmmm!"
      redirect_to rating_path(@rating)
    else
      render :new
    end
  end

  def show
    @rating = Rating.find(params[:rating_id])
    @recipe = Recipe.find(params[:id])
    render :show
  end

  def edit
    @rating = Rating.find(params[:rating_id])
    @recipe = Recipe.find(params[:id])
    render :edit
  end

  def update
    @rating = Rating.find(params[:rating_id])
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:alert] = "You updated that!"
      redirect_to rating_path(@recipe.rating)
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to rating_path(@recipe.rating)
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :instructions, :search)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_recipe_form.html.erb
<%= render "layouts/errors", :object => @recipe %>

<%= form_for [@rating, @recipe] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :ingredients %>
  <%= f.text_area :ingredients %>
  <%= f.label :instructions %>
  <%= f.text_area :instructions %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/edit.html.erb
<h1>Edit rating</h1>

<%= form_for @rating do |f| %>
  <%= f.label :difficulty %>
  <%= f.text_field :difficulty %>
  <%= f.submit  %>
<% end %>

app/views/ratings/index.html.erb
<h1>Difficulty</h1>

<% if @ratings.any? %>

  <ul>
    <% @ratings.each do |rating| %>
      <li><%= link_to rating.difficulty, rating_path(rating) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no ratings yet.</p>
<% end %>


<p><%= link_to "Create new rating", new_rating_path %></p>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= form_for @rating do |f| %>
  <%= f.label :difficulty %>
  <%= f.text_field :difficulty %>
  <%= f.submit  %>
<% end %>  

app/views/ratings/show.html.erb
<h1><%= @rating.difficulty %></h1>
<form>
  <label for="">Search by title</label>
  <input type="text" name="search">
  <button type="submit" name="button">go</button>
</form>

<% if @recipes.any? %>
  <h4>Here are the recipes for this rating:</h4>

  <% @recipes.each do |recipe| %>
    <ul>
      <li>
        <%= link_to recipe.title, rating_recipe_path(@rating, recipe) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No recipes are listed for this rating.</p>
<% end %>

<p><%= link_to "Add a recipe", new_rating_recipe_path(@rating) %></p>

<p><%= link_to "Edit", edit_rating_path(@rating) %></p>
<p><%= link_to "Delete rating", rating_path(@rating),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to ratings", ratings_path %></p>

app/views/recipes/edit.html.erb
<h1>Edit recipe:</h1>


<%= render "layouts/recipe_form" %>

app/views/recipes/new.html.erb
<h1>Add a new recipe:</h1>

<%= form_for [@rating, @recipe] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :ingredients %>
  <%= f.text_area :ingredients %>
  <%= f.label :instructions %>
  <%= f.text_area :instructions %>
  <p><%= f.submit %></p>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipe: <%= @recipe.title %></h1>
<h2>Rating: <%= @rating.difficulty %></h2>
  <h4>Ingredients:</h4>
  <ul>
  <% @recipe.ingredients.gsub(/\W/, " ").split(" ").each do |ingredient| %>
      <li>
        <%= ingredient %>
      </li>
  <% end %>
</ul>
<h3>Instructions: <%= @recipe.instructions %></h3>


<p><%= link_to "Edit recipe", edit_rating_recipe_path(@rating, @recipe) %></p>
<p><%= link_to "Delete recipe", rating_recipe_path(@rating, @recipe),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to rating", rating_path(@rating) %></p>